# Generated by Django 2.0.2 on 2018-03-21 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoIntern', '0002_auto_20180308_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=255)),
                ('doc_date', models.CharField(max_length=255)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='document_folder')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoIntern.User'),
        ),
    ]
